name: Run Tests on Push

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: hellorobotinc/stretch-install-image
      volumes:
        - /dev:/dev
      network: host

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure Git to trust the directory
      run: git config --global --add safe.directory `pwd`
    - name: Get LFS objects
      run: git lfs pull
    - name: Install dependencies and code
      run: |
        python
        python -m pip install -e ./src[dev]
    - name: Run tests
      run: |
        python -m pip install pytest
        pytest body/test/test_foo.py