name: Run Tests on Push

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: hellorobotinc/stretch-install-image:0.0.1
      # options: --userns=host --privileged
      options: --user 1000:1000
      volumes:
        - /dev:/dev

    steps:
    - uses: actions/checkout@v4
    - name: Configure working direcotry
      run: |
        echo "Current directory is $(pwd)"
        echo "Present files are $(ls)"
        git config --global --add safe.directory `pwd`
    - name: Install Stretch Body
      run: |
        source /home/hello-robot/.bashrc
        pip3 install -e body/
    - name: Run Stretch Body Tests
      run: |
        pytest-3 body/test/robot_tests