name: Checkout new PR
on:
  pull_request_target:
jobs:
  Checkout_PR_and_run_tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: save the ssh key for access to robot to the file
        run: 'echo "$SSH_KEY" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }}
      - run: chmod 400 the_key

      - name: Print out PR reference values
        run: |
          echo github.base_ref: ${{ github.base_ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}

      - name: Replace PR number, Branch name and Cloning URL
        run: sed -e "s/\$1/${PR_NUMBER}/g" -e "s|\$2|${BRANCH_NAME}|g" -e "s|\$3|${CLONE_URL}|g" .github/workflows/pr_checkout_commands.sh > ssh_commands_pr_info.sh; cat ssh_commands_pr_info.sh
        env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
          CLONE_URL: ${{ github.event.repository.clone_url }}

      - name: Log into stretch using ssh and run tests
        run: ssh -i the_key hello-robot@"${STRETCH_IP}" -p "$STRETCH_PORT" -tt -o StrictHostKeyChecking=no < ./ssh_commands_pr_info.sh
        env:
          STRETCH_IP: 72.134.86.243
          STRETCH_PORT: 43771